package com.model;
// Generated Nov 26, 2022 10:26:00 PM by Hibernate Tools 4.3.5.Final

/**
 * Danhgia generated by hbm2java
 */
public class Danhgia implements java.io.Serializable {

	private Integer madanhgia;
	private Baiviet baiviet;
	private String binhluan;
	private Integer diem;

	public Danhgia() {
	}

	public Danhgia(Baiviet baiviet) {
		this.baiviet = baiviet;
	}

	public Danhgia(Baiviet baiviet, String binhluan, Integer diem) {
		this.baiviet = baiviet;
		this.binhluan = binhluan;
		this.diem = diem;
	}

	public Integer getMadanhgia() {
		return this.madanhgia;
	}

	public void setMadanhgia(Integer madanhgia) {
		this.madanhgia = madanhgia;
	}

	public Baiviet getBaiviet() {
		return this.baiviet;
	}

	public void setBaiviet(Baiviet baiviet) {
		this.baiviet = baiviet;
	}

	public String getBinhluan() {
		return this.binhluan;
	}

	public void setBinhluan(String binhluan) {
		this.binhluan = binhluan;
	}

	public Integer getDiem() {
		return this.diem;
	}

	public void setDiem(Integer diem) {
		this.diem = diem;
	}

}
