package com.model;
// Generated Nov 21, 2022 3:37:39 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Baiviet generated by hbm2java
 */
@Entity
@Table(name = "baiviet", catalog = "dbqbamthuc")
public class Baiviet implements java.io.Serializable {

	private Integer mabaiviet;
	private Nguoidung nguoidung;
	private String tenbaiviet;
	private String mota;
	private String nguyenlieu;
	private String cachlam;
	private String hinh;
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);
	private Set<Theloai> theloais = new HashSet<Theloai>(0);

	public Baiviet() {
	}

	public Baiviet(Nguoidung nguoidung, String tenbaiviet, String mota, String nguyenlieu, String cachlam) {
		this.nguoidung = nguoidung;
		this.tenbaiviet = tenbaiviet;
		this.mota = mota;
		this.nguyenlieu = nguyenlieu;
		this.cachlam = cachlam;
	}

	public Baiviet(Nguoidung nguoidung, String tenbaiviet, String mota, String nguyenlieu, String cachlam, String hinh,
			Set<Danhgia> danhgias, Set<Theloai> theloais) {
		this.nguoidung = nguoidung;
		this.tenbaiviet = tenbaiviet;
		this.mota = mota;
		this.nguyenlieu = nguyenlieu;
		this.cachlam = cachlam;
		this.hinh = hinh;
		this.danhgias = danhgias;
		this.theloais = theloais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mabaiviet", unique = true, nullable = false)
	public Integer getMabaiviet() {
		return this.mabaiviet;
	}

	public void setMabaiviet(Integer mabaiviet) {
		this.mabaiviet = mabaiviet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manguoidung", nullable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

	@Column(name = "tenbaiviet", nullable = false, length = 100)
	public String getTenbaiviet() {
		return this.tenbaiviet;
	}

	public void setTenbaiviet(String tenbaiviet) {
		this.tenbaiviet = tenbaiviet;
	}

	@Column(name = "mota", nullable = false, length = 65535)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "nguyenlieu", nullable = false, length = 65535)
	public String getNguyenlieu() {
		return this.nguyenlieu;
	}

	public void setNguyenlieu(String nguyenlieu) {
		this.nguyenlieu = nguyenlieu;
	}

	@Column(name = "cachlam", nullable = false, length = 65535)
	public String getCachlam() {
		return this.cachlam;
	}

	public void setCachlam(String cachlam) {
		this.cachlam = cachlam;
	}

	@Column(name = "hinh", length = 65535)
	public String getHinh() {
		return this.hinh;
	}

	public void setHinh(String hinh) {
		this.hinh = hinh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baiviet")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "theloai_baiviet", catalog = "dbqbamthuc", joinColumns = {
			@JoinColumn(name = "mabaiviet", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "matheloai", nullable = false, updatable = false) })
	public Set<Theloai> getTheloais() {
		return this.theloais;
	}

	public void setTheloais(Set<Theloai> theloais) {
		this.theloais = theloais;
	}

}
