package com.model;
// Generated Nov 21, 2022 3:37:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Danhgia generated by hbm2java
 */
@Entity
@Table(name = "danhgia", catalog = "dbqbamthuc")
public class Danhgia implements java.io.Serializable {

	private Integer madanhgia;
	private Baiviet baiviet;
	private String binhluan;
	private Integer diem;

	public Danhgia() {
	}

	public Danhgia(Baiviet baiviet) {
		this.baiviet = baiviet;
	}

	public Danhgia(Baiviet baiviet, String binhluan, Integer diem) {
		this.baiviet = baiviet;
		this.binhluan = binhluan;
		this.diem = diem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "madanhgia", unique = true, nullable = false)
	public Integer getMadanhgia() {
		return this.madanhgia;
	}

	public void setMadanhgia(Integer madanhgia) {
		this.madanhgia = madanhgia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mabaiviet", nullable = false)
	public Baiviet getBaiviet() {
		return this.baiviet;
	}

	public void setBaiviet(Baiviet baiviet) {
		this.baiviet = baiviet;
	}

	@Column(name = "binhluan", length = 65535)
	public String getBinhluan() {
		return this.binhluan;
	}

	public void setBinhluan(String binhluan) {
		this.binhluan = binhluan;
	}

	@Column(name = "diem")
	public Integer getDiem() {
		return this.diem;
	}

	public void setDiem(Integer diem) {
		this.diem = diem;
	}

}
