package com.model;
// Generated Nov 21, 2022 3:37:39 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "nguoidung", catalog = "dbqbamthuc", uniqueConstraints = @UniqueConstraint(columnNames = "sodienthoai"))
public class Nguoidung implements java.io.Serializable {

	private Integer manguoidung;
	private String tennguoidung;
	private String sodienthoai;
	private Date ngaysinh;
	private String hinhdaidien;
	private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);
	private Set<Baiviet> baiviets = new HashSet<Baiviet>(0);

	public Nguoidung() {
	}

	public Nguoidung(String tennguoidung, String sodienthoai, Date ngaysinh) {
		this.tennguoidung = tennguoidung;
		this.sodienthoai = sodienthoai;
		this.ngaysinh = ngaysinh;
	}

	public Nguoidung(String tennguoidung, String sodienthoai, Date ngaysinh, String hinhdaidien,
			Set<Taikhoan> taikhoans, Set<Baiviet> baiviets) {
		this.tennguoidung = tennguoidung;
		this.sodienthoai = sodienthoai;
		this.ngaysinh = ngaysinh;
		this.hinhdaidien = hinhdaidien;
		this.taikhoans = taikhoans;
		this.baiviets = baiviets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "manguoidung", unique = true, nullable = false)
	public Integer getManguoidung() {
		return this.manguoidung;
	}

	public void setManguoidung(Integer manguoidung) {
		this.manguoidung = manguoidung;
	}

	@Column(name = "tennguoidung", nullable = false, length = 30)
	public String getTennguoidung() {
		return this.tennguoidung;
	}

	public void setTennguoidung(String tennguoidung) {
		this.tennguoidung = tennguoidung;
	}

	@Column(name = "sodienthoai", unique = true, nullable = false, length = 10)
	public String getSodienthoai() {
		return this.sodienthoai;
	}

	public void setSodienthoai(String sodienthoai) {
		this.sodienthoai = sodienthoai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", nullable = false, length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "hinhdaidien", length = 65535)
	public String getHinhdaidien() {
		return this.hinhdaidien;
	}

	public void setHinhdaidien(String hinhdaidien) {
		this.hinhdaidien = hinhdaidien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nguoidung")
	public Set<Taikhoan> getTaikhoans() {
		return this.taikhoans;
	}

	public void setTaikhoans(Set<Taikhoan> taikhoans) {
		this.taikhoans = taikhoans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nguoidung")
	public Set<Baiviet> getBaiviets() {
		return this.baiviets;
	}

	public void setBaiviets(Set<Baiviet> baiviets) {
		this.baiviets = baiviets;
	}

}
