package com.model;
// Generated Nov 21, 2022 3:37:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaikhoanId generated by hbm2java
 */
@Embeddable
public class TaikhoanId implements java.io.Serializable {

	private String tentaikhoan;
	private String matkhau;
	private int manguoidung;

	public TaikhoanId() {
	}

	public TaikhoanId(String tentaikhoan, String matkhau, int manguoidung) {
		this.tentaikhoan = tentaikhoan;
		this.matkhau = matkhau;
		this.manguoidung = manguoidung;
	}

	@Column(name = "tentaikhoan", unique = true, nullable = false, length = 30)
	public String getTentaikhoan() {
		return this.tentaikhoan;
	}

	public void setTentaikhoan(String tentaikhoan) {
		this.tentaikhoan = tentaikhoan;
	}

	@Column(name = "matkhau", nullable = false, length = 10)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "manguoidung", nullable = false)
	public int getManguoidung() {
		return this.manguoidung;
	}

	public void setManguoidung(int manguoidung) {
		this.manguoidung = manguoidung;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaikhoanId))
			return false;
		TaikhoanId castOther = (TaikhoanId) other;

		return ((this.getTentaikhoan() == castOther.getTentaikhoan()) || (this.getTentaikhoan() != null
				&& castOther.getTentaikhoan() != null && this.getTentaikhoan().equals(castOther.getTentaikhoan())))
				&& ((this.getMatkhau() == castOther.getMatkhau()) || (this.getMatkhau() != null
						&& castOther.getMatkhau() != null && this.getMatkhau().equals(castOther.getMatkhau())))
				&& (this.getManguoidung() == castOther.getManguoidung());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTentaikhoan() == null ? 0 : this.getTentaikhoan().hashCode());
		result = 37 * result + (getMatkhau() == null ? 0 : this.getMatkhau().hashCode());
		result = 37 * result + this.getManguoidung();
		return result;
	}

}
