package com.model;
// Generated Nov 21, 2022 3:37:39 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "dbqbamthuc", uniqueConstraints = @UniqueConstraint(columnNames = "tentaikhoan"))
public class Taikhoan implements java.io.Serializable {

	private TaikhoanId id;
	private Nguoidung nguoidung;

	public Taikhoan() {
	}

	public Taikhoan(TaikhoanId id, Nguoidung nguoidung) {
		this.id = id;
		this.nguoidung = nguoidung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tentaikhoan", column = @Column(name = "tentaikhoan", unique = true, nullable = false, length = 30)),
			@AttributeOverride(name = "matkhau", column = @Column(name = "matkhau", nullable = false, length = 10)),
			@AttributeOverride(name = "manguoidung", column = @Column(name = "manguoidung", nullable = false)) })
	public TaikhoanId getId() {
		return this.id;
	}

	public void setId(TaikhoanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manguoidung", nullable = false, insertable = false, updatable = false)
	public Nguoidung getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(Nguoidung nguoidung) {
		this.nguoidung = nguoidung;
	}

}
